# Generated by Django 4.1.3 on 2022-11-05 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_data',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url_data',
            name='url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
