# Generated by Django 4.1.3 on 2022-11-05 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_url_data_count_alter_url_data_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Url_Data',
        ),
    ]
