# Generated by Django 4.1.3 on 2022-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0003_web_url_delete_url_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_url',
            name='short',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
